// Felix, Eric Donner
// 2024/05/30
// Easy Track Inventory Application
// Add window

package easytrack;

import static easytrack.EasyTrackMainMenu.monitors;

public class EasyTrackAdd extends javax.swing.JFrame {
    
    EasyTrackMainMenu EasyTrackMainMenu; // main menu class
    
    // variables for the new object to be created
    int hardwareType;
    int assetNumber;
    int location;
    int purchasedType;
    String vendor;
    String model;
    String serialNumber;
    String deviceName;
    String printerLocation;
    boolean as400OutQ;
    String as400Name;
    boolean chequePrinter;
    boolean colourPrinter;
    String faxNumber;
    String employeeAssignment;
    String dellServiceTag;
    String macAddress;
    String ipAddress1;
    String ipAddress2;
    String ipAddress3;
    String iloIPAddress;
    String notes;

    /**
     * Creates new form EasyTrackAdd
     */
    public EasyTrackAdd(EasyTrackMainMenu m) {
        initComponents();
        EasyTrackMainMenu = m;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        backButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        hardwareTypeComboBox = new javax.swing.JComboBox<>();
        assetNumberLabel = new javax.swing.JLabel();
        assetNumberTextField = new javax.swing.JTextField();
        locationComboBox = new javax.swing.JComboBox<>();
        purchaseTypeComboBox = new javax.swing.JComboBox<>();
        vendorLabel = new javax.swing.JLabel();
        vendorTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        serialNumberLabel = new javax.swing.JLabel();
        serialNumberTextField = new javax.swing.JTextField();
        notesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();
        printerLocationLabel = new javax.swing.JLabel();
        printerLocationTextField = new javax.swing.JTextField();
        as400outqLabel = new javax.swing.JLabel();
        as400outqNameTextField = new javax.swing.JTextField();
        as400outqNameLabel = new javax.swing.JLabel();
        chequePrinterLabel = new javax.swing.JLabel();
        yesButton1 = new javax.swing.JRadioButton();
        noButton1 = new javax.swing.JRadioButton();
        yesButton2 = new javax.swing.JRadioButton();
        noButton2 = new javax.swing.JRadioButton();
        colourPrinterLabel = new javax.swing.JLabel();
        yesButton3 = new javax.swing.JRadioButton();
        noButton3 = new javax.swing.JRadioButton();
        faxNumberLabel = new javax.swing.JLabel();
        faxNumberTextField = new javax.swing.JTextField();
        employeeAssignmentLabel = new javax.swing.JLabel();
        employeeAssignmentTextField = new javax.swing.JTextField();
        dellServiceTagLabel = new javax.swing.JLabel();
        dellServiceTagTextField = new javax.swing.JTextField();
        deviceNameLabel = new javax.swing.JLabel();
        deviceNameTextField = new javax.swing.JTextField();
        macAddressLabel = new javax.swing.JLabel();
        macAddressTextField = new javax.swing.JTextField();
        ip1Label = new javax.swing.JLabel();
        ip1TextField = new javax.swing.JTextField();
        ip2Label = new javax.swing.JLabel();
        ip2TextField = new javax.swing.JTextField();
        ip3Label = new javax.swing.JLabel();
        ip3TextField = new javax.swing.JTextField();
        iloipLabel = new javax.swing.JLabel();
        iloipTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setText("Return to Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addButton.setText("Add Item");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setText("Add New Item");

        warningLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        warningLabel.setText("Leave fields blank if they do not apply");

        hardwareTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Server", "Desktop", "Laptop", "Thin Client", "Monitor", "Firewall", "Wireless Access Point", "Network Switch", "UPS", "Printer/Copier", "Scanner", "Timeclock", "Tape Drive", "SAN", "Fiber Switch" }));

        assetNumberLabel.setText("Asset Number:");

        assetNumberTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        assetNumberTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        assetNumberTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mid-Range", "Toronto", "St. John's", "Montreal", "Calgary", "Winnipeg", "Surrey", "IT Storage", "Employee's Home" }));

        purchaseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Purchased", "Leased" }));

        vendorLabel.setText("Vendor:");

        vendorTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        vendorTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        vendorTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        modelLabel.setText("Model:");

        modelTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        modelTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        modelTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        serialNumberLabel.setText("Serial Number:");

        serialNumberTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        serialNumberTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        serialNumberTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        notesLabel.setText("Notes:");

        notesTextArea.setColumns(20);
        notesTextArea.setRows(5);
        jScrollPane1.setViewportView(notesTextArea);

        printerLocationLabel.setText("Printer Location:");

        printerLocationTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        printerLocationTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        printerLocationTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        as400outqLabel.setText("AS400 OUTQ:");

        as400outqNameTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        as400outqNameTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        as400outqNameTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        as400outqNameLabel.setText("AS400 OUTQ Name:");

        chequePrinterLabel.setText("Cheque Printer:");

        buttonGroup1.add(yesButton1);
        yesButton1.setText("Yes");

        buttonGroup1.add(noButton1);
        noButton1.setText("No");

        buttonGroup2.add(yesButton2);
        yesButton2.setText("Yes");

        buttonGroup2.add(noButton2);
        noButton2.setText("No");

        colourPrinterLabel.setText("Colour Printer:");

        buttonGroup3.add(yesButton3);
        yesButton3.setText("Yes");

        buttonGroup3.add(noButton3);
        noButton3.setText("No");

        faxNumberLabel.setText("Fax Number:");

        faxNumberTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        faxNumberTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        faxNumberTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        employeeAssignmentLabel.setText("Employee Assignment:");

        employeeAssignmentTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        employeeAssignmentTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        employeeAssignmentTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        dellServiceTagLabel.setText("Dell Service Tag:");

        dellServiceTagTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        dellServiceTagTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        dellServiceTagTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        deviceNameLabel.setText("Device Name:");

        deviceNameTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        deviceNameTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        deviceNameTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        macAddressLabel.setText("MAC Address:");

        macAddressTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        macAddressTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        macAddressTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        ip1Label.setText("IP Address 1:");

        ip1TextField.setMaximumSize(new java.awt.Dimension(123, 22));
        ip1TextField.setMinimumSize(new java.awt.Dimension(123, 22));
        ip1TextField.setPreferredSize(new java.awt.Dimension(123, 22));

        ip2Label.setText("IP Address 2:");

        ip2TextField.setMaximumSize(new java.awt.Dimension(123, 22));
        ip2TextField.setMinimumSize(new java.awt.Dimension(123, 22));
        ip2TextField.setPreferredSize(new java.awt.Dimension(123, 22));

        ip3Label.setText("IP Address 3:");

        ip3TextField.setMaximumSize(new java.awt.Dimension(123, 22));
        ip3TextField.setMinimumSize(new java.awt.Dimension(123, 22));
        ip3TextField.setPreferredSize(new java.awt.Dimension(123, 22));

        iloipLabel.setText("ILO IP Address:");

        iloipTextField.setMaximumSize(new java.awt.Dimension(123, 22));
        iloipTextField.setMinimumSize(new java.awt.Dimension(123, 22));
        iloipTextField.setPreferredSize(new java.awt.Dimension(123, 22));

        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearButton.setText("Clear Fields");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(warningLabel)
                        .addComponent(hardwareTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(assetNumberLabel)
                            .addGap(18, 18, 18)
                            .addComponent(assetNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(purchaseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vendorLabel)
                                .addComponent(modelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vendorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modelTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(serialNumberLabel)
                            .addGap(18, 18, 18)
                            .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(deviceNameLabel)
                            .addGap(18, 18, 18)
                            .addComponent(deviceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addButton)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(printerLocationLabel)
                                    .addComponent(as400outqLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(printerLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yesButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(noButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(as400outqNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(as400outqNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(colourPrinterLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chequePrinterLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yesButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yesButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(noButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(noButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(faxNumberLabel)
                                .addGap(18, 18, 18)
                                .addComponent(faxNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeeAssignmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(employeeAssignmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dellServiceTagLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dellServiceTagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(macAddressLabel)
                                .addGap(18, 18, 18)
                                .addComponent(macAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(156, 156, 156)
                        .addComponent(clearButton)
                        .addGap(81, 81, 81)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ip1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(ip2Label)
                            .addComponent(ip3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ip1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ip2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ip3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iloipLabel)
                        .addGap(18, 18, 18)
                        .addComponent(iloipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warningLabel)
                    .addComponent(printerLocationLabel)
                    .addComponent(printerLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ip1Label)
                    .addComponent(ip1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hardwareTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(as400outqLabel)
                    .addComponent(yesButton1)
                    .addComponent(noButton1)
                    .addComponent(ip2Label)
                    .addComponent(ip2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetNumberLabel)
                    .addComponent(assetNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(as400outqNameLabel)
                    .addComponent(as400outqNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ip3Label)
                    .addComponent(ip3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chequePrinterLabel)
                    .addComponent(yesButton2)
                    .addComponent(noButton2)
                    .addComponent(iloipLabel)
                    .addComponent(iloipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colourPrinterLabel)
                            .addComponent(yesButton3)
                            .addComponent(noButton3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendorLabel)
                            .addComponent(vendorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faxNumberLabel)
                            .addComponent(faxNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelLabel)
                            .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeAssignmentLabel)
                            .addComponent(employeeAssignmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serialNumberLabel)
                            .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dellServiceTagLabel)
                            .addComponent(dellServiceTagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deviceNameLabel)
                            .addComponent(deviceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(macAddressLabel)
                            .addComponent(macAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(addButton)
                            .addComponent(clearButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(notesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(12, 12, 12)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // go back to main menu
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        EasyTrackMainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    // add object to coresponding file and array list
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // get all of the fields values from the GUI and place into variables
        hardwareType = hardwareTypeComboBox.getSelectedIndex();
        assetNumber = Integer.parseInt(assetNumberTextField.getText());
        location = locationComboBox.getSelectedIndex();
        purchasedType = purchaseTypeComboBox.getSelectedIndex();
        vendor = vendorTextField.getText();
        model = modelTextField.getText();
        serialNumber = serialNumberTextField.getText();
        deviceName = deviceNameTextField.getText();
        printerLocation = printerLocationTextField.getText();
        as400OutQ = yesButton1.isSelected();
        as400Name = as400outqNameTextField.getText();
        chequePrinter = yesButton2.isSelected();
        colourPrinter = yesButton3.isSelected();
        faxNumber = faxNumberTextField.getText();
        employeeAssignment = employeeAssignmentTextField.getText();
        dellServiceTag = dellServiceTagTextField.getText();
        macAddress = macAddressTextField.getText();
        ipAddress1 = ip1TextField.getText();
        ipAddress2 = ip2TextField.getText();
        ipAddress3 = ip3TextField.getText();
        iloIPAddress = iloipTextField.getText();
        notes = notesTextArea.getText();

        // if object is a server
        if (hardwareType == 0) {
            // create server object
            Server s1 = new Server(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3, dellServiceTag, iloIPAddress);
            
            // put server object into server arraylist
            EasyTrackMainMenu.getServers().add(s1);
            
        } else if (hardwareType == 1) { // if object is a desktop
            // create desktop object
            Desktop d1 = new Desktop(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3, dellServiceTag);
           
            // put desktop object into desktop arraylist
            EasyTrackMainMenu.getDesktops().add(d1);
            
        } else if (hardwareType == 2) { // if object is a laptop
            //create laptop object
            Laptop l1 = new Laptop(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3, employeeAssignment, dellServiceTag);
            
            // put laptop object into laptop arraylist
            EasyTrackMainMenu.getLaptops().add(l1);
            
        } else if (hardwareType == 3) { // if object is a thin client
            // create thin client object
            ThinClient tc1 = new ThinClient(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, dellServiceTag);
            
            // put thin client object into thin client arraylist
            EasyTrackMainMenu.getThinClients().add(tc1);
            
        } else if (hardwareType == 4) { // if object is a monitor
            // create monitor object
            Monitor m1 = new Monitor(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, employeeAssignment, dellServiceTag);
            
            // put monitor object into monitor arraylist
            EasyTrackMainMenu.getMonitors().add(m1);
            
        } else if (hardwareType == 5) { // if object is a firewall
            // create firewall object
            FireWall f1 = new FireWall(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put firewall object into firewall arraylist
            EasyTrackMainMenu.getFirewalls().add(f1);
            
        } else if (hardwareType == 6) { // if object is a wireless access point
            // create wireless access point object
            WAP wap1 = new WAP(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put wireless access point object into wap arraylist
            EasyTrackMainMenu.getWap().add(wap1);
            
        } else if (hardwareType == 7) { // if object is a network switch
            // create network switch object
            NetworkSwitch ns1 = new NetworkSwitch(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put network switch object into network switch arraylist
            EasyTrackMainMenu.getNetworkSwitch().add(ns1);
            
        } else if (hardwareType == 8) { // if object is a ups
            // create ups object
            UPS ups1 = new UPS(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put ups object into ups arraylist
            EasyTrackMainMenu.getUps().add(ups1);
            
        } else if (hardwareType == 9) { // if object is a printer/copier
            // create printer object
            Printer p1 = new Printer(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, macAddress, ipAddress1, ipAddress2, ipAddress3, printerLocation, as400OutQ, as400Name, chequePrinter, colourPrinter, faxNumber);
            
            // put printer object into printer arraylist
            EasyTrackMainMenu.getPrinters().add(p1);
            
        } else if (hardwareType == 10) { // if object is a scanner
            // create scanner object
            Scanner s1 = new Scanner(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, printerLocation);
            
            // put scanner object into scanner arraylist
            EasyTrackMainMenu.getScanners().add(s1);
            
        } else if (hardwareType == 11) { // if object is a timeclock
            // create timeclock object
            TimeClock tc1 = new TimeClock(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put timeclock object into timeclock arraylist
            EasyTrackMainMenu.getTimeClocks().add(tc1);
            
        } else if (hardwareType == 12) { // if object is a tapedrive
            // create tapedrive object
            TapeDrive td1 = new TapeDrive(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put tapedrive object into tapedrive arraylist
            EasyTrackMainMenu.getTapeDrive().add(td1);
            
        } else if (hardwareType == 13) { // if object is a san
            // create san object
            SAN san1 = new SAN(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put san object into san arraylist
            EasyTrackMainMenu.getSan().add(san1);
            
        } else if (hardwareType == 14) { // if object is a fiber switch
            // create fiber switch object
            FiberSwitch fs1 = new FiberSwitch(assetNumber, location, true, vendor, model, serialNumber, purchasedType, notes, deviceName, macAddress, ipAddress1, ipAddress2, ipAddress3);
            
            // put fiber switch object into fiber switch arraylist
            EasyTrackMainMenu.getFiberSwitch().add(fs1);
            
        }
    }//GEN-LAST:event_addButtonActionPerformed

    // clears all fields in window
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // reset all text fields/areas, buttons and combo boxes
        as400outqNameTextField.setText("");
        assetNumberTextField.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        dellServiceTagTextField.setText("");
        deviceNameTextField.setText("");
        employeeAssignmentTextField.setText("");
        faxNumberTextField.setText("");
        hardwareTypeComboBox.setSelectedIndex(0);
        iloipTextField.setText("");
        ip1TextField.setText("");
        ip2TextField.setText("");
        ip3TextField.setText("");
        locationComboBox.setSelectedIndex(0);
        macAddressTextField.setText("");
        modelTextField.setText("");
        notesTextArea.setText("");
        printerLocationTextField.setText("");
        purchaseTypeComboBox.setSelectedIndex(0);
        serialNumberTextField.setText("");
        vendorTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel as400outqLabel;
    private javax.swing.JLabel as400outqNameLabel;
    private javax.swing.JTextField as400outqNameTextField;
    private javax.swing.JLabel assetNumberLabel;
    private javax.swing.JTextField assetNumberTextField;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel chequePrinterLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel colourPrinterLabel;
    private javax.swing.JLabel dellServiceTagLabel;
    private javax.swing.JTextField dellServiceTagTextField;
    private javax.swing.JLabel deviceNameLabel;
    private javax.swing.JTextField deviceNameTextField;
    private javax.swing.JLabel employeeAssignmentLabel;
    private javax.swing.JTextField employeeAssignmentTextField;
    private javax.swing.JLabel faxNumberLabel;
    private javax.swing.JTextField faxNumberTextField;
    private javax.swing.JComboBox<String> hardwareTypeComboBox;
    private javax.swing.JLabel iloipLabel;
    private javax.swing.JTextField iloipTextField;
    private javax.swing.JLabel ip1Label;
    private javax.swing.JTextField ip1TextField;
    private javax.swing.JLabel ip2Label;
    private javax.swing.JTextField ip2TextField;
    private javax.swing.JLabel ip3Label;
    private javax.swing.JTextField ip3TextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JLabel macAddressLabel;
    private javax.swing.JTextField macAddressTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JRadioButton noButton1;
    private javax.swing.JRadioButton noButton2;
    private javax.swing.JRadioButton noButton3;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JTextArea notesTextArea;
    private javax.swing.JLabel printerLocationLabel;
    private javax.swing.JTextField printerLocationTextField;
    private javax.swing.JComboBox<String> purchaseTypeComboBox;
    private javax.swing.JLabel serialNumberLabel;
    private javax.swing.JTextField serialNumberTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JTextField vendorTextField;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JRadioButton yesButton1;
    private javax.swing.JRadioButton yesButton2;
    private javax.swing.JRadioButton yesButton3;
    // End of variables declaration//GEN-END:variables
}